# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 523f4e7c7a7209c3cf511778e43318d26b3f9a03154706591136c8db346543a636d3d3095aac1299de99bcd345d112c81c4a2974bfc7026d9a281769421eb9be

test:
  secret_key_base: 5a06645481fdb3d1975e3983095ef79c773ff51c98c2599e76ed1673ee767b20c6b74e4f2bffa4fb9d4497af30bfed22b42f9bdd29f7e3e8a1f0f7d2ba53de47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
